export const __esModule: true
export const container: string
export const gwCol: string
export const negative: string
export const numCol: string
export const playerCell: string
export const positive: string
export const table: string
export const tcBadge: string
export const templateCell: string
export const totalLabel: string
export const totalRow: string
