export const __esModule: true
export const cell: string
export const center: string
export const error: string
export const errorHint: string
export const errorTitle: string
export const fixturesTest: string
export const header: string
export const headerCell: string
export const live: string
export const loading: string
export const muted: string
export const row: string
export const score: string
export const table: string
export const tableBody: string
export const tableHead: string
export const title: string
