export const __esModule: true
export const arrow: string
export const captainName: string
export const captainRow: string
export const captainsList: string
export const captainsPanel: string
export const deadline: string
export const emptyMessage: string
export const gameweekDetails: string
export const header: string
export const hitBadge: string
export const hitTag: string
export const miniSection: string
export const miniTitle: string
export const panelTitle: string
export const playerIn: string
export const playerOut: string
export const tag: string
export const tagBadge: string
export const tagList: string
export const tagName: string
export const teamName: string
export const title: string
export const topRow: string
export const transferIcon: string
export const transferItem: string
export const transferMove: string
export const transferMoves: string
export const transferTeam: string
export const transfersGrid: string
export const transfersSection: string
