export const __esModule: true
export const arrow: string
export const bottomRow: string
export const captainName: string
export const captainRow: string
export const captainsList: string
export const captainsPanel: string
export const container: string
export const deadline: string
export const emptyMessage: string
export const header: string
export const hitBadge: string
export const hitTag: string
export const hitsAmount: string
export const hitsList: string
export const hitsName: string
export const hitsPanel: string
export const hitsRank: string
export const hitsRow: string
export const mainRow: string
export const miniSection: string
export const miniTitle: string
export const panelTitle: string
export const playerIn: string
export const playerOut: string
export const tag: string
export const tagBadge: string
export const tagList: string
export const tagName: string
export const teamName: string
export const title: string
export const topRow: string
export const transferIcon: string
export const transferItem: string
export const transferMove: string
export const transferMoves: string
export const transferTeam: string
export const transfersGrid: string
export const transfersSection: string
export const valueAmount: string
export const valueName: string
export const valueRank: string
export const valueRow: string
export const valuesList: string
export const valuesPanel: string
