export const __esModule: true
export const bonusPoints: string
export const bonusRow: string
export const defconLabel: string
export const defconRow: string
export const fixtureCard: string
export const fixtureGrid: string
export const fixtureHeader: string
export const gameRewards: string
export const playerNames: string
export const rewardsList: string
export const score: string
export const statusMessage: string
export const teamName: string
export const title: string
