export const __esModule: true
export const captain: string
export const cell: string
export const center: string
export const chip: string
export const colCaptain: string
export const colChip: string
export const colGw: string
export const colManager: string
export const colRank: string
export const colTotal: string
export const container: string
export const down: string
export const gwPoints: string
export const header: string
export const headerCell: string
export const liveBadge: string
export const manager: string
export const muted: string
export const playerName: string
export const provisionalBonus: string
export const pulse: string
export const rank: string
export const rankChange: string
export const rankNumber: string
export const row: string
export const table: string
export const tableBody: string
export const tableHead: string
export const teamName: string
export const teamNameIcon: string
export const title: string
export const totalPoints: string
export const up: string
