export const __esModule: true;
export const backdropAppear: string;
export const body: string;
export const closeButton: string;
export const content: string;
export const dialogAppear: string;
export const header: string;
export const Modal: string;
export const title: string;
