export const __esModule: true
export const badge: string
export const closeButton: string
export const icon: string
export const link: string
export const message: string
export const ReleaseNotification: string
export const separator: string
export const version: string
