export const __esModule: true
export const best: string
export const card: string
export const chartContainer: string
export const chartInner: string
export const chartSection: string
export const chartTitle: string
export const empty: string
export const error: string
export const legendText: string
export const loading: string
export const miniCard: string
export const miniCardContent: string
export const miniCardLabel: string
export const miniCardValue: string
export const miniCards: string
export const positionGrid: string
export const positionItem: string
export const positionLabel: string
export const positionPercentage: string
export const positionPoints: string
export const positionSection: string
export const tooltip: string
export const tooltipDot: string
export const tooltipLabel: string
export const tooltipRow: string
export const tooltipTitle: string
export const tooltipValue: string
export const totalItem: string
export const totalLabel: string
export const totalValue: string
export const totals: string
export const worst: string
