export const __esModule: true
export const active: string
export const additionalStats: string
export const bonusCircle: string
export const delta: string
export const deltaItem: string
export const deltaItems: string
export const deltaLabel: string
export const deltaLegend: string
export const deltaValue: string
export const deltasRow: string
export const easy: string
export const empty: string
export const fdrBadge: string
export const fdrGw: string
export const fdrTeam: string
export const fdrVenue: string
export const fixtureList: string
export const formIndicator: string
export const formSame: string
export const gwIcon: string
export const gwIcons: string
export const gwLabel: string
export const gwMinutes: string
export const gwOpponent: string
export const gwPoints: string
export const gwXStats: string
export const hard: string
export const header: string
export const headerGw: string
export const headerIcons: string
export const headerInfo: string
export const headerMins: string
export const headerOpponent: string
export const headerPts: string
export const headerXStats: string
export const historyHeader: string
export const historyItem: string
export const historyList: string
export const historyListExpanded: string
export const iconCount: string
export const loading: string
export const medium: string
export const nameRow: string
export const negative: string
export const news: string
export const ownership: string
export const photo: string
export const PlayerModal: string
export const playerName: string
export const positionBadge: string
export const positive: string
export const price: string
export const priceChange: string
export const priceRow: string
export const seasonRow: string
export const section: string
export const sectionLoading: string
export const sectionTitle: string
export const showMoreButton: string
export const statCard: string
export const statDetail: string
export const statLabel: string
export const statPer90: string
export const statValue: string
export const statsGrid: string
export const status: string
export const tabButton: string
export const tabButtons: string
export const tabContent: string
export const tabSection: string
export const teamName: string
export const teamRow: string
