export const __esModule: true
export const bonusCircle: string
export const cell: string
export const colGw: string
export const colIcons: string
export const colMin: string
export const colOpponent: string
export const colPts: string
export const colXstats: string
export const empty: string
export const expanded: string
export const headerCell: string
export const headerRow: string
export const historyTable: string
export const icon: string
export const icons: string
export const row: string
export const showMoreButton: string
export const table: string
export const tableWrapper: string
