export const __esModule: true
export const Account: string
export const card: string
export const cardHeader: string
export const cardTitle: string
export const consentWarning: string
export const content: string
export const error: string
export const form: string
export const futureCard: string
export const futureText: string
export const futureTitle: string
export const header: string
export const hint: string
export const input: string
export const inputError: string
export const inputGroup: string
export const label: string
export const loggedIn: string
export const logoutButton: string
export const status: string
export const submitButton: string
export const subtitle: string
export const title: string
