export const __esModule: true
export const Analytics: string
export const error: string
export const loading: string
export const section: string
export const sectionTitle: string
export const spin: string
export const spinner: string
export const title: string
