export const __esModule: true
export const arrow: string
export const bottomSection: string
export const Dashboard: string
export const error: string
export const errorHint: string
export const gameweekLabel: string
export const grid: string
export const lastUpdated: string
export const liveIndicator: string
export const loading: string
export const mainColumn: string
export const playerIn: string
export const playerOut: string
export const pulse: string
export const refreshButton: string
export const retryButton: string
export const shimmer: string
export const sideColumn: string
export const skeleton: string
export const skeletonContent: string
export const skeletonTitle: string
export const spin: string
export const spinner: string
export const statusBar: string
export const statusInfo: string
export const transferIcon: string
export const transferItem: string
export const transferMove: string
export const transferMoves: string
export const transferTeam: string
export const transfersCard: string
export const transfersFlow: string
export const transfersTitle: string
