export const __esModule: true
export const board: string
export const card: string
export const cardDescription: string
export const cardTitle: string
export const cards: string
export const column: string
export const columnHeader: string
export const columnSubtitle: string
export const columnTitle: string
export const content: string
export const empty: string
export const header: string
export const later: string
export const next: string
export const now: string
export const Roadmap: string
export const subtitle: string
export const title: string
